name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Load SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Add known_hosts
      run: |
        ssh-keyscan -H brick.01z.io >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Run deploy
      run: ./deploy.sh
